apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-auto
  name: web-auto
  namespace: automation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-auto
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-auto
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}

